name: build
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '14'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
          channel: stable
      - name: Build apk
        run: |
          flutter pub get
          flutter analyze
          flutter test
          flutter build apk --debug
