name: build
on: push
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '14.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
          channel: stable
      - name: Build apk
        run: |
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter test
          flutter build apk --debug
